// Sık kullanılan Linux komutları ve Türkçe açıklamaları.
// Öneri listesinde komut yazılırken açıklamasıyla birlikte gösterilir.

export interface CommandInfo {
  cmd: string
  desc: string
}

const RAW: Array<[string, string]> = [
  // Dosya ve klasör
  ['ls', 'Klasör içeriğini listeler'],
  ['ls -la', 'Gizli dosyalar dahil ayrıntılı liste'],
  ['ls -lh', 'Boyutları okunur biçimde listeler'],
  ['ls -lt', 'Değiştirilme zamanına göre sıralı liste'],
  ['cd', 'Klasör değiştirir'],
  ['cd ..', 'Üst klasöre çıkar'],
  ['cd ~', 'Ev klasörüne gider'],
  ['cd -', 'Önceki klasöre döner'],
  ['pwd', 'Bulunduğunuz klasörün yolunu yazar'],
  ['mkdir', 'Klasör oluşturur'],
  ['mkdir -p', 'İç içe klasörleri birlikte oluşturur'],
  ['rm', 'Dosya siler'],
  ['rm -rf', 'Klasörü içeriğiyle birlikte zorla siler (dikkat!)'],
  ['rmdir', 'Boş klasörü siler'],
  ['cp', 'Dosya kopyalar'],
  ['cp -r', 'Klasörü içeriğiyle kopyalar'],
  ['mv', 'Dosya taşır ya da yeniden adlandırır'],
  ['touch', 'Boş dosya oluşturur / tarihini günceller'],
  ['ln -s', 'Sembolik bağlantı oluşturur'],
  ['find . -name', 'Adına göre dosya arar'],
  ['find . -type f -mtime -1', 'Son 24 saatte değişen dosyalar'],
  ['tree', 'Klasör yapısını ağaç olarak gösterir'],
  ['stat', 'Dosyanın ayrıntılı bilgisini gösterir'],
  ['file', 'Dosyanın türünü söyler'],
  ['realpath', 'Dosyanın tam yolunu yazar'],
  // Dosya içeriği
  ['cat', 'Dosya içeriğini yazdırır'],
  ['less', 'Dosyayı sayfa sayfa okur'],
  ['head', 'Dosyanın ilk satırlarını gösterir'],
  ['head -n 50', 'İlk 50 satırı gösterir'],
  ['tail', 'Dosyanın son satırlarını gösterir'],
  ['tail -f', 'Dosyayı canlı izler (loglar için)'],
  ['tail -n 100 -f', 'Son 100 satırı gösterip canlı izler'],
  ['nano', 'Basit metin düzenleyici'],
  ['vim', 'Gelişmiş metin düzenleyici'],
  ['vi', 'Metin düzenleyici'],
  ['grep', 'Metin içinde arama yapar'],
  ['grep -rn', 'Klasörlerde satır numarasıyla arar'],
  ['grep -i', 'Büyük/küçük harf duyarsız arar'],
  ['wc -l', 'Satır sayısını sayar'],
  ['sort', 'Satırları sıralar'],
  ['uniq -c', 'Tekrarları sayarak birleştirir'],
  ['diff', 'İki dosyayı karşılaştırır'],
  ['awk', 'Metin işleme dili'],
  ['sed -i', 'Dosyada bul-değiştir yapar'],
  ['echo', 'Metin yazdırır'],
  ['tee', 'Çıktıyı hem ekrana hem dosyaya yazar'],
  ['xargs', 'Girdiyi komut argümanına çevirir'],
  // Sıkıştırma
  ['tar -czvf', 'Klasörü .tar.gz olarak sıkıştırır'],
  ['tar -xzvf', '.tar.gz arşivini açar'],
  ['tar -tzvf', 'Arşiv içeriğini listeler'],
  ['zip -r', 'Klasörü zip olarak sıkıştırır'],
  ['unzip', 'Zip arşivini açar'],
  ['gzip', 'Dosyayı gzip ile sıkıştırır'],
  // İzinler ve kullanıcılar
  ['chmod', 'Dosya izinlerini değiştirir'],
  ['chmod +x', 'Dosyayı çalıştırılabilir yapar'],
  ['chmod -R 755', 'İzinleri klasörde toplu değiştirir'],
  ['chown', 'Dosya sahibini değiştirir'],
  ['chown -R', 'Sahipliği klasörde toplu değiştirir'],
  ['sudo', 'Komutu yönetici yetkisiyle çalıştırır'],
  ['sudo -i', 'Root kabuğuna geçer'],
  ['su -', 'Başka kullanıcıya geçer'],
  ['whoami', 'Hangi kullanıcı olduğunuzu yazar'],
  ['id', 'Kullanıcı ve grup kimliklerini gösterir'],
  ['passwd', 'Parola değiştirir'],
  ['useradd -m', 'Ev klasörüyle yeni kullanıcı ekler'],
  ['usermod -aG', 'Kullanıcıyı gruba ekler'],
  ['who', 'Oturum açmış kullanıcıları listeler'],
  ['last', 'Son oturum açmaları gösterir'],
  // Sistem
  ['top', 'Canlı işlem ve kaynak kullanımı'],
  ['htop', 'Renkli, etkileşimli işlem görüntüleyici'],
  ['ps aux', 'Tüm çalışan işlemleri listeler'],
  ['ps aux | grep', 'Çalışan işlemlerde arama yapar'],
  ['kill', 'İşlemi sonlandırır'],
  ['kill -9', 'İşlemi zorla sonlandırır'],
  ['pkill', 'Adına göre işlem sonlandırır'],
  ['df -h', 'Disk doluluk durumunu gösterir'],
  ['du -sh', 'Klasör boyutunu gösterir'],
  ['du -sh * | sort -h', 'Klasördeki öğeleri boyuta göre sıralar'],
  ['free -h', 'Bellek (RAM) kullanımını gösterir'],
  ['uptime', 'Sistemin ne kadar süredir açık olduğunu gösterir'],
  ['uname -a', 'Çekirdek ve sistem bilgisi'],
  ['hostnamectl', 'Sunucu adı ve işletim sistemi bilgisi'],
  ['lsb_release -a', 'Dağıtım sürümünü gösterir'],
  ['cat /etc/os-release', 'İşletim sistemi sürümünü gösterir'],
  ['lscpu', 'İşlemci bilgisi'],
  ['lsblk', 'Diskleri ve bölümleri listeler'],
  ['mount', 'Bağlı dosya sistemlerini gösterir'],
  ['reboot', 'Sunucuyu yeniden başlatır'],
  ['shutdown -h now', 'Sunucuyu hemen kapatır'],
  ['history', 'Komut geçmişini gösterir'],
  ['clear', 'Ekranı temizler'],
  ['exit', 'Oturumu kapatır'],
  ['date', 'Tarih ve saati gösterir'],
  ['timedatectl', 'Saat dilimi ve zaman ayarları'],
  ['crontab -e', 'Zamanlanmış görevleri düzenler'],
  ['crontab -l', 'Zamanlanmış görevleri listeler'],
  ['watch -n 2', 'Komutu 2 saniyede bir tekrar çalıştırır'],
  ['env', 'Ortam değişkenlerini listeler'],
  ['export', 'Ortam değişkeni tanımlar'],
  ['which', 'Komutun dosya yolunu bulur'],
  ['man', 'Komutun kılavuzunu açar'],
  ['screen', 'Kopmaya dayanıklı terminal oturumu'],
  ['tmux', 'Terminal çoklayıcı'],
  ['tmux attach', 'Var olan tmux oturumuna bağlanır'],
  // Servisler ve loglar
  ['systemctl status', 'Servisin durumunu gösterir'],
  ['systemctl restart', 'Servisi yeniden başlatır'],
  ['systemctl start', 'Servisi başlatır'],
  ['systemctl stop', 'Servisi durdurur'],
  ['systemctl enable --now', 'Servisi açılışta başlat ve şimdi çalıştır'],
  ['systemctl disable', 'Servisin açılışta başlamasını kapatır'],
  ['systemctl daemon-reload', 'Servis dosyalarını yeniden yükler'],
  ['systemctl list-units --type=service', 'Servisleri listeler'],
  ['journalctl -u', 'Bir servisin loglarını gösterir'],
  ['journalctl -fu', 'Servis loglarını canlı izler'],
  ['journalctl -xe', 'Son sistem hatalarını ayrıntılı gösterir'],
  ['service', 'Servis yönetimi (eski sistemler)'],
  ['dmesg -T', 'Çekirdek mesajlarını gösterir'],
  // Paket yönetimi
  ['apt update', 'Paket listesini günceller'],
  ['apt upgrade', 'Yüklü paketleri yükseltir'],
  ['apt install', 'Paket kurar'],
  ['apt remove', 'Paket kaldırır'],
  ['apt search', 'Paket arar'],
  ['sudo apt update && sudo apt upgrade -y', 'Sistemi tamamen günceller'],
  ['dnf install', 'Paket kurar (Fedora/RHEL)'],
  ['yum install', 'Paket kurar (CentOS)'],
  ['apk add', 'Paket kurar (Alpine)'],
  ['snap install', 'Snap paketi kurar'],
  ['pip install', 'Python paketi kurar'],
  ['npm install', 'Node.js bağımlılıklarını kurar'],
  ['npm run', 'package.json betiği çalıştırır'],
  // Ağ
  ['ping', 'Sunucuya erişilebilirliği test eder'],
  ['curl', 'HTTP isteği yapar'],
  ['curl -I', 'Sadece HTTP başlıklarını getirir'],
  ['curl -O', 'Dosyayı indirir'],
  ['wget', 'Dosya indirir'],
  ['ip a', 'Ağ arayüzlerini ve IP adreslerini gösterir'],
  ['ip route', 'Yönlendirme tablosunu gösterir'],
  ['ss -tulpn', 'Dinlenen portları ve işlemleri gösterir'],
  ['netstat -tulpn', 'Açık portları gösterir'],
  ['dig', 'DNS sorgusu yapar'],
  ['nslookup', 'Alan adının IP adresini sorgular'],
  ['traceroute', 'Paketlerin izlediği yolu gösterir'],
  ['ufw status', 'Güvenlik duvarı durumunu gösterir'],
  ['ufw allow', 'Güvenlik duvarında port açar'],
  ['iptables -L -n', 'Güvenlik duvarı kurallarını listeler'],
  ['scp', 'SSH ile dosya kopyalar'],
  ['rsync -avz', 'Dosyaları verimli şekilde eşitler'],
  ['ssh', 'Başka bir sunucuya SSH ile bağlanır'],
  ['ssh-keygen -t ed25519', 'Yeni SSH anahtarı üretir'],
  // Git
  ['git status', 'Çalışma dizininin durumunu gösterir'],
  ['git pull', 'Uzaktaki değişiklikleri çeker'],
  ['git push', 'Commit\'leri uzağa gönderir'],
  ['git add .', 'Tüm değişiklikleri hazırlar'],
  ['git commit -m', 'Mesajla commit oluşturur'],
  ['git log --oneline', 'Commit geçmişini kısa gösterir'],
  ['git diff', 'Değişiklikleri gösterir'],
  ['git checkout', 'Dal değiştirir'],
  ['git checkout -b', 'Yeni dal oluşturup geçer'],
  ['git branch', 'Dalları listeler'],
  ['git clone', 'Depoyu kopyalar'],
  ['git stash', 'Değişiklikleri geçici olarak saklar'],
  ['git reset --hard', 'Değişiklikleri kalıcı olarak geri alır (dikkat!)'],
  // Docker
  ['docker ps', 'Çalışan konteynerleri listeler'],
  ['docker ps -a', 'Tüm konteynerleri listeler'],
  ['docker images', 'İmajları listeler'],
  ['docker logs -f', 'Konteyner loglarını canlı izler'],
  ['docker exec -it', 'Konteyner içinde komut çalıştırır'],
  ['docker restart', 'Konteyneri yeniden başlatır'],
  ['docker stop', 'Konteyneri durdurur'],
  ['docker rm', 'Konteyneri siler'],
  ['docker pull', 'İmaj indirir'],
  ['docker stats', 'Konteyner kaynak kullanımını gösterir'],
  ['docker system prune', 'Kullanılmayan veriyi temizler'],
  ['docker compose up -d', 'Servisleri arka planda başlatır'],
  ['docker compose down', 'Servisleri durdurup kaldırır'],
  ['docker compose logs -f', 'Tüm servis loglarını izler'],
  ['docker compose ps', 'Compose servislerini listeler'],
  ['docker compose pull', 'Güncel imajları indirir'],
  // Web sunucuları ve veritabanları
  ['nginx -t', 'Nginx yapılandırmasını test eder'],
  ['systemctl reload nginx', 'Nginx\'i kesintisiz yeniden yükler'],
  ['certbot --nginx', 'Nginx için SSL sertifikası alır'],
  ['mysql -u root -p', 'MySQL\'e root olarak bağlanır'],
  ['psql -U postgres', 'PostgreSQL\'e bağlanır'],
  ['redis-cli', 'Redis komut satırı'],
  ['pm2 list', 'PM2 uygulamalarını listeler'],
  ['pm2 logs', 'PM2 loglarını izler'],
  ['pm2 restart', 'PM2 uygulamasını yeniden başlatır'],
  // Kubernetes
  ['kubectl get pods', 'Pod\'ları listeler'],
  ['kubectl get pods -A', 'Tüm namespace\'lerdeki pod\'lar'],
  ['kubectl logs -f', 'Pod loglarını izler'],
  ['kubectl describe pod', 'Pod ayrıntılarını gösterir'],
  ['kubectl exec -it', 'Pod içinde komut çalıştırır'],
  ['kubectl apply -f', 'YAML dosyasını uygular']
]

export const COMMANDS: CommandInfo[] = RAW.map(([cmd, desc]) => ({ cmd, desc }))

/** Yazım düzeltmesi için bilinen komut adları (ilk kelime). */
export const COMMAND_NAMES: string[] = [...new Set(RAW.map(([c]) => c.split(' ')[0]))]

/** Argümanı bir dosya/klasör yolu olan komutlar. */
export const PATH_COMMANDS = new Set([
  'cd', 'ls', 'cat', 'less', 'more', 'head', 'tail', 'nano', 'vim', 'vi', 'rm', 'cp', 'mv', 'touch', 'mkdir', 'rmdir',
  'chmod', 'chown', 'stat', 'file', 'source', '.', 'bash', 'sh', 'python', 'python3', 'node', 'tar', 'unzip', 'zip',
  'du', 'grep', 'diff', 'tree', 'code', 'realpath', 'ln', 'scp', 'rsync', 'gzip', 'gunzip', 'find', 'wc', 'sort', 'open'
])

export const DIR_ONLY_COMMANDS = new Set(['cd', 'rmdir', 'pushd'])
